shopware:
  baseUri:
  username:
  password:
  exportedAttribute:
  orderFilters:
    - property:
      value:
      expression:

mailbluster:
  baseUri:
  apiKey:
  requestsPerMinute: 55
  campaignMappings: []
  campaignMappingPassThroughPattern:

logging:
  file:
    path: /log