x-restart-policy: &restart-policy
  restart: unless-stopped

version: "2.4"
services:
  showpare-mailbluster-sync:
    image: peaceman/shopware5-mailbluster-sync:${APP_VERSION}
    <<: *restart-policy
    volumes:
      - ./application.yml:/workspace/application.yml